services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wishlist_data:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app
      - media_data:/app/media
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '9000:9000'
    healthcheck:
      test: ping 0.0.0.0 -p 9000 -c 1
      interval: 60s
      timeout: 10s
      retries: 1

  redis:
    image: redis:7.4.2
    ports:
      - '6379:6379'

  celery:
    build: .
    volumes:
      - .:/app
    command: ./celery_tasks/start_celery.sh
    depends_on:
      - redis

  celery-beat:
    build: .
    volumes:
      - .:/app
    command: ./celery_tasks/start_celery_beat.sh
    depends_on:
      - redis

  flower:
    image: mher/flower:2.0.1
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
    ports:
      - "5555:5555"
    depends_on:
      - redis

volumes:
  wishlist_data: { }
  media_data: { }
