services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - wishlist_data:/var/lib/postgresql/data

  api:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:9000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '9000:9000'
    healthcheck:
      test: ping 0.0.0.0 -p 9000 -c 1
      interval: 60s
      timeout: 10s
      retries: 1

volumes:
  wishlist_data:

