# Generated by Django 5.2 on 2025-04-20 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wish',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
