# Generated by Django 5.2 on 2025-04-21 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0002_wish_description_alter_wish_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wish_images'),
        ),
    ]
