# Generated by Django 5.2 on 2025-04-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0003_alter_wish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
